Debug: false
BackItemInCosmeticsMenu: true
Final-Kill-Suffix: "&b&lFINAL KILL!"
# plugins/BW1058-Cosmetics/Sprays
Spray-Dir: "Sprays"
mysql:
  enable: false
  host: "localhost"
  port: 3306
  database: "name"
  username: "root"
  password: "none"
  maxpoolsize: 50
cosmetic-preview:
  cosmetic-location:
    world:
    x:
    y:
    z:
    yaw:
    pitch:
  player-location:
    world:
    x:
    y:
    z:
    yaw:
    pitch:
bed-break-effects:
  enabled: true
death-cries:
  enabled:true
final-kill-effects:
  enabled: true
glyphs:
  enabled: true
island-toppers:
  enabled: true
  order: true
kill-messages:
  enabled: true
projectile-trails:
  enabled: true
shopkeeper-skins:
  enabled: true
sprays:
  enabled: true
victory-dances:
  enabled: true
wood-skins:
  enabled: true