Debug: false
BackItemInCosmeticsMenu: true
Final-Kill-Suffix: "&b&lFINAL KILL!"
mysql:
  enable: false
  host: "localhost"
  port: "3306"
  database: "name"
  username: "root"
  password: "none"
cosmetic-preview:
  cosmetic-location:
    world:
    x:
    y:
    z:
    yaw:
    pitch:
  player-location:
    world:
    x:
    y:
    z:
    yaw:
    pitch: